name: "validate in docker"
on:
  pull_request:
  push:
    branches: [ stable ]
jobs:
  build_in_docker:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distrib: [ ubuntu-bionic, ubuntu-xenial, centos7 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          BASE_IMAGE: ${{ matrix.distrib }}
          PARALLELISM: 2
        run: |
          ./tests/test_in_docker
